# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: systrace.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='systrace.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0esystrace.proto\".\n\nStackFrame\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\x04\x12\x0f\n\x07so_name\x18\x02 \x01(\t\"\x89\x01\n\rMemAllocEntry\x12\x11\n\talloc_ptr\x18\x01 \x01(\x04\x12\x10\n\x08stage_id\x18\x02 \x01(\r\x12\x1e\n\nstage_type\x18\x03 \x01(\x0e\x32\n.StageType\x12\x10\n\x08mem_size\x18\x04 \x01(\x04\x12!\n\x0cstack_frames\x18\x05 \x03(\x0b\x32\x0b.StackFrame\"!\n\x0cMemFreeEntry\x12\x11\n\talloc_ptr\x18\x01 \x01(\x04\"h\n\x07ProcMem\x12\x0b\n\x03pid\x18\x01 \x01(\r\x12(\n\x10mem_alloc_stacks\x18\x02 \x03(\x0b\x32\x0e.MemAllocEntry\x12&\n\x0fmem_free_stacks\x18\x03 \x03(\x0b\x32\r.MemFreeEntry\"7\n\x0bGcDebugData\x12\x11\n\tcollected\x18\x01 \x01(\r\x12\x15\n\runcollectable\x18\x02 \x01(\r\"\x9c\x01\n\x0cPytorchStage\x12\x10\n\x08stage_id\x18\x01 \x01(\r\x12\x12\n\nstage_type\x18\x02 \x01(\t\x12\x10\n\x08start_us\x18\x03 \x01(\x04\x12\x0e\n\x06\x65nd_us\x18\x04 \x01(\x04\x12\x14\n\x0cstack_frames\x18\x05 \x03(\t\x12 \n\x08gc_debug\x18\x06 \x01(\x0b\x32\x0c.GcDebugDataH\x00\x42\x0c\n\ndebug_data\"]\n\x07Pytorch\x12%\n\x0epytorch_stages\x18\x01 \x03(\x0b\x32\r.PytorchStage\x12\x0c\n\x04rank\x18\x02 \x01(\r\x12\x0f\n\x07step_id\x18\x03 \x01(\r\x12\x0c\n\x04\x63omm\x18\x04 \x01(\t\"!\n\x03Mem\x12\x1a\n\x08proc_mem\x18\x01 \x03(\x0b\x32\x08.ProcMem*\x84\x01\n\tStageType\x12\x11\n\rSTAGE_UNKNOWN\x10\x00\x12\x14\n\x10STAGE_DATALOADER\x10\x01\x12\x11\n\rSTAGE_FORWARD\x10\x02\x12\x12\n\x0eSTAGE_BACKWARD\x10\x03\x12\x19\n\x15STAGE_SYNCHRONIZATION\x10\x04\x12\x0c\n\x08STAGE_GC\x10\x05\x62\x06proto3'
)

_STAGETYPE = _descriptor.EnumDescriptor(
  name='StageType',
  full_name='StageType',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STAGE_UNKNOWN', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAGE_DATALOADER', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAGE_FORWARD', index=2, number=2,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAGE_BACKWARD', index=3, number=3,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAGE_SYNCHRONIZATION', index=4, number=4,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='STAGE_GC', index=5, number=5,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=694,
  serialized_end=826,
)
_sym_db.RegisterEnumDescriptor(_STAGETYPE)

StageType = enum_type_wrapper.EnumTypeWrapper(_STAGETYPE)
STAGE_UNKNOWN = 0
STAGE_DATALOADER = 1
STAGE_FORWARD = 2
STAGE_BACKWARD = 3
STAGE_SYNCHRONIZATION = 4
STAGE_GC = 5



_STACKFRAME = _descriptor.Descriptor(
  name='StackFrame',
  full_name='StackFrame',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='address', full_name='StackFrame.address', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='so_name', full_name='StackFrame.so_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=64,
)


_MEMALLOCENTRY = _descriptor.Descriptor(
  name='MemAllocEntry',
  full_name='MemAllocEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alloc_ptr', full_name='MemAllocEntry.alloc_ptr', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_id', full_name='MemAllocEntry.stage_id', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_type', full_name='MemAllocEntry.stage_type', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mem_size', full_name='MemAllocEntry.mem_size', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stack_frames', full_name='MemAllocEntry.stack_frames', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=67,
  serialized_end=204,
)


_MEMFREEENTRY = _descriptor.Descriptor(
  name='MemFreeEntry',
  full_name='MemFreeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='alloc_ptr', full_name='MemFreeEntry.alloc_ptr', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=239,
)


_PROCMEM = _descriptor.Descriptor(
  name='ProcMem',
  full_name='ProcMem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pid', full_name='ProcMem.pid', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mem_alloc_stacks', full_name='ProcMem.mem_alloc_stacks', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mem_free_stacks', full_name='ProcMem.mem_free_stacks', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=241,
  serialized_end=345,
)


_GCDEBUGDATA = _descriptor.Descriptor(
  name='GcDebugData',
  full_name='GcDebugData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='collected', full_name='GcDebugData.collected', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='uncollectable', full_name='GcDebugData.uncollectable', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=347,
  serialized_end=402,
)


_PYTORCHSTAGE = _descriptor.Descriptor(
  name='PytorchStage',
  full_name='PytorchStage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='stage_id', full_name='PytorchStage.stage_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stage_type', full_name='PytorchStage.stage_type', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='start_us', full_name='PytorchStage.start_us', index=2,
      number=3, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='end_us', full_name='PytorchStage.end_us', index=3,
      number=4, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='stack_frames', full_name='PytorchStage.stack_frames', index=4,
      number=5, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gc_debug', full_name='PytorchStage.gc_debug', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='debug_data', full_name='PytorchStage.debug_data',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=405,
  serialized_end=561,
)


_PYTORCH = _descriptor.Descriptor(
  name='Pytorch',
  full_name='Pytorch',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pytorch_stages', full_name='Pytorch.pytorch_stages', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rank', full_name='Pytorch.rank', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='step_id', full_name='Pytorch.step_id', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='comm', full_name='Pytorch.comm', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=563,
  serialized_end=656,
)


_MEM = _descriptor.Descriptor(
  name='Mem',
  full_name='Mem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='proc_mem', full_name='Mem.proc_mem', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=658,
  serialized_end=691,
)

_MEMALLOCENTRY.fields_by_name['stage_type'].enum_type = _STAGETYPE
_MEMALLOCENTRY.fields_by_name['stack_frames'].message_type = _STACKFRAME
_PROCMEM.fields_by_name['mem_alloc_stacks'].message_type = _MEMALLOCENTRY
_PROCMEM.fields_by_name['mem_free_stacks'].message_type = _MEMFREEENTRY
_PYTORCHSTAGE.fields_by_name['gc_debug'].message_type = _GCDEBUGDATA
_PYTORCHSTAGE.oneofs_by_name['debug_data'].fields.append(
  _PYTORCHSTAGE.fields_by_name['gc_debug'])
_PYTORCHSTAGE.fields_by_name['gc_debug'].containing_oneof = _PYTORCHSTAGE.oneofs_by_name['debug_data']
_PYTORCH.fields_by_name['pytorch_stages'].message_type = _PYTORCHSTAGE
_MEM.fields_by_name['proc_mem'].message_type = _PROCMEM
DESCRIPTOR.message_types_by_name['StackFrame'] = _STACKFRAME
DESCRIPTOR.message_types_by_name['MemAllocEntry'] = _MEMALLOCENTRY
DESCRIPTOR.message_types_by_name['MemFreeEntry'] = _MEMFREEENTRY
DESCRIPTOR.message_types_by_name['ProcMem'] = _PROCMEM
DESCRIPTOR.message_types_by_name['GcDebugData'] = _GCDEBUGDATA
DESCRIPTOR.message_types_by_name['PytorchStage'] = _PYTORCHSTAGE
DESCRIPTOR.message_types_by_name['Pytorch'] = _PYTORCH
DESCRIPTOR.message_types_by_name['Mem'] = _MEM
DESCRIPTOR.enum_types_by_name['StageType'] = _STAGETYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StackFrame = _reflection.GeneratedProtocolMessageType('StackFrame', (_message.Message,), {
  'DESCRIPTOR' : _STACKFRAME,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:StackFrame)
  })
_sym_db.RegisterMessage(StackFrame)

MemAllocEntry = _reflection.GeneratedProtocolMessageType('MemAllocEntry', (_message.Message,), {
  'DESCRIPTOR' : _MEMALLOCENTRY,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:MemAllocEntry)
  })
_sym_db.RegisterMessage(MemAllocEntry)

MemFreeEntry = _reflection.GeneratedProtocolMessageType('MemFreeEntry', (_message.Message,), {
  'DESCRIPTOR' : _MEMFREEENTRY,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:MemFreeEntry)
  })
_sym_db.RegisterMessage(MemFreeEntry)

ProcMem = _reflection.GeneratedProtocolMessageType('ProcMem', (_message.Message,), {
  'DESCRIPTOR' : _PROCMEM,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:ProcMem)
  })
_sym_db.RegisterMessage(ProcMem)

GcDebugData = _reflection.GeneratedProtocolMessageType('GcDebugData', (_message.Message,), {
  'DESCRIPTOR' : _GCDEBUGDATA,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:GcDebugData)
  })
_sym_db.RegisterMessage(GcDebugData)

PytorchStage = _reflection.GeneratedProtocolMessageType('PytorchStage', (_message.Message,), {
  'DESCRIPTOR' : _PYTORCHSTAGE,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:PytorchStage)
  })
_sym_db.RegisterMessage(PytorchStage)

Pytorch = _reflection.GeneratedProtocolMessageType('Pytorch', (_message.Message,), {
  'DESCRIPTOR' : _PYTORCH,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:Pytorch)
  })
_sym_db.RegisterMessage(Pytorch)

Mem = _reflection.GeneratedProtocolMessageType('Mem', (_message.Message,), {
  'DESCRIPTOR' : _MEM,
  '__module__' : 'systrace_pb2'
  # @@protoc_insertion_point(class_scope:Mem)
  })
_sym_db.RegisterMessage(Mem)


# @@protoc_insertion_point(module_scope)
